- name: Create kubeconfig directory
  file:
    path: '{{ kube_config|dirname }}'
    state: directory
    mode: 0755

- name: Create empty kubeconfig
  file:
    path: '{{ kube_config }}'
    state: touch
    mode: 0644

- name: Check whether cluster is currently running
  command: kubectl cluster-info
  register: cluster_info
  failed_when: false

- name: Debug cluster_info
  debug:
    var: cluster_info

- name: Create cluster
  when: cluster_info.rc != 0
  block:
  - name: Initialize the master node
    command: >-
      kubeadm init --apiserver-advertise-address={{ ansible_host }}
                   --apiserver-cert-extra-sans={{ ansible_host }}
                   --node-name={{ inventory_hostname }}
                   --pod-network-cidr=10.244.0.0/16

  - name: Copy default configuration
    copy:
      src: /etc/kubernetes/admin.conf
      dest: '{{ kube_config }}'
      owner: '{{ ansible_user }}'
      group: '{{ ansible_user }}'
      mode: 0644
      remote_src: yes

  - name: Install flannel
    shell: >-
      wget -q -O - https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml
      | yq '.spec.template.spec.containers[0].args += "--iface=eth1"'
      | kubectl apply -f -

  - name: Allow non-critical workloads on master nodes
    command: kubectl taint nodes '{{ inventory_hostname }}' node-role.kubernetes.io/master:NoSchedule-

  - name: Get join command
    command: kubeadm token create --print-join-command
    register: join_command

  - name: Write join command to local file
    copy:
      content: '{{ join_command.stdout_lines[0] }}'
      dest: .join-command
    become: no
    delegate_to: localhost
