apiVersion: v1
kind: Pod
metadata:
  labels:
    jenkins: slave
    jenkins/label: jenkins-slave
  name: jenkins-slave
spec:
  restartPolicy: Never
  containers:
  - name: ansible-runner
    image: emandret/ansible-alpine
    imagePullPolicy: IfNotPresent
    command: [sleep]
    args: ['9999999']
    resources:
      limits:
        memory: 512Mi
        cpu: '0.1'
      requests:
        memory: 256Mi
        cpu: '0.1'
    volumeMounts:
    - mountPath: /var/playbooks
      name: ansible-hostpath
  volumes:
  - hostPath:
    name: ansible-hostpath
    path: /nfs/playbooks
